(function(){
function q(s){return document.querySelector(s)} function qa(s){return document.querySelectorAll(s)}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
var api=(window.APTV_CONFIG&&window.APTV_CONFIG.youtubeSearchApiUrl)||'https://aptv-two.vercel.app/api/youtube-search';
var status=q('#searchStatus'), results=q('#ytResults'), input=q('#ytSearch'), currentVideo=null, ytPlayer=null, ytReady=false, retryTimer=null, browseScroll=0, lastItems=[];
function render(items){lastItems=items||[];results.innerHTML='';for(var i=0;i<items.length;i++){(function(v){var b=document.createElement('button');b.className='video-card focusable';b.innerHTML='<img src="'+esc(v.thumbnail||('https://i.ytimg.com/vi/'+v.id+'/mqdefault.jpg'))+'"><b>'+esc(v.title||'Video')+'</b><small>'+esc(v.channel||'YouTube')+'</small>';b.onclick=function(){play(v)};results.appendChild(b)})(items[i])}}
function search(term){if(!term)return;status.textContent='Đang tìm “'+term+'”...';var x=new XMLHttpRequest();x.open('GET',api+'?q='+encodeURIComponent(term),true);x.onreadystatechange=function(){if(x.readyState!==4)return;if(x.status>=200&&x.status<300){try{var d=JSON.parse(x.responseText);render(d.items||[]);status.textContent=(d.items||[]).length+' kết quả cho “'+term+'”'}catch(e){status.textContent='Lỗi đọc kết quả YouTube.'}}else status.textContent='Không lấy được kết quả YouTube.'};x.send()}
function makePlayer(v,autoPlay){currentVideo=v;var box=q('#modalPlayer');box.innerHTML='';if(window.YT&&window.YT.Player){ytPlayer=new YT.Player('modalPlayer',{width:'100%',height:'100%',videoId:v.id,playerVars:{playsinline:1,rel:0,autoplay:autoPlay?1:0},events:{onReady:function(e){ytReady=true;if(autoPlay){try{e.target.playVideo()}catch(x){}}},onError:function(){q('#modalHelp').textContent='Video không phát được trong trình nhúng. Có thể mở YouTube gốc.'}}});}else{box.innerHTML='<iframe style="width:100%;height:100%;border:0" src="https://www.youtube.com/embed/'+encodeURIComponent(v.id)+'?enablejsapi=1&playsinline=1&rel=0" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>';}}
function play(v){if(document.body.className.indexOf('youtube-split')>=0){browseScroll=results?results.scrollTop:0;currentVideo=v;try{var hist=JSON.parse(localStorage.getItem('aptvRecent')||'[]');hist=hist.filter(function(x){return x.id!==v.id});hist.unshift(v);localStorage.setItem('aptvRecent',JSON.stringify(hist.slice(0,18)))}catch(e){}var f=q('#youtubeFrame'),ph=q('#playerPlaceholder'),wrap=q('#playerWrap'),orig=q('#inlineOriginal');document.body.className=document.body.className.replace(/\s*player-mode/g,'')+' player-mode';if(f){f.src='https://www.youtube.com/embed/'+encodeURIComponent(v.id)+'?autoplay=1&playsinline=1&rel=0';f.style.display='block'}if(ph)ph.style.display='none';if(wrap)wrap.className=wrap.className.replace(/\s*playing/g,'')+' playing';if(orig)orig.href='https://www.youtube.com/watch?v='+v.id;var ic=q('#inlineControls'),cv=q('#changeVideo');if(ic)ic.className=ic.className.replace(/\s*hidden/g,'');if(cv)cv.className=cv.className.replace(/\s*hidden/g,'');return}var m=q('#videoModal'),title=q('#modalTitle'),ch=q('#modalChannel'),orig=q('#modalOriginal');currentVideo=v;title.textContent=v.title||'YouTube';ch.textContent=v.channel||'YouTube';orig.href='https://www.youtube.com/watch?v='+v.id;m.classList.remove('hidden');m.classList.add('velora-open');q('#modalHelp').textContent='Đang tải trình phát… Nếu không tự chạy, chạm ▶ Phát hoặc ↻ Thử lại.';makePlayer(v,true)}
q('#ytSearchBtn').onclick=function(){search(input.value.replace(/^\s+|\s+$/g,''))};input.onkeydown=function(e){e=e||window.event;if((e.keyCode||e.which)===13)search(input.value.replace(/^\s+|\s+$/g,''))};
var cats=qa('[data-yt-query]');for(var i=0;i<cats.length;i++)cats[i].onclick=function(){input.value=this.getAttribute('data-yt-query');search(input.value)};
var chips=qa('[data-query]');for(var j=0;j<chips.length;j++)chips[j].onclick=function(){input.value=this.getAttribute('data-query');search(input.value)};
q('#swapBtn').onclick=function(){var w=q('.workspace');if(w.className.indexOf('swapped-layout')>=0)w.className=w.className.replace(/\s*swapped-layout/g,'');else w.className+=' swapped-layout'};
q('#modalClose').onclick=function(){var m=q('#videoModal');m.classList.add('hidden');m.classList.remove('velora-open');try{if(ytPlayer&&ytPlayer.stopVideo)ytPlayer.stopVideo()}catch(e){}q('#modalPlayer').innerHTML='';ytPlayer=null;ytReady=false};q('#videoModal').onclick=function(e){if(e.target===q('#videoModal'))q('#modalClose').click()};
q('#modalPlay').onclick=function(){if(!currentVideo)return;if(ytPlayer&&ytReady&&ytPlayer.playVideo){try{ytPlayer.playVideo();q('#modalHelp').textContent='Đang phát...';return}catch(e){}}makePlayer(currentVideo,true);q('#modalHelp').textContent='Đang yêu cầu phát video...'};
q('#modalRetry').onclick=function(){if(!currentVideo)return;var b=q('#modalRetry');b.disabled=true;b.textContent='↻ Đang tải lại…';q('#modalHelp').textContent='Đang tạo lại trình phát YouTube…';try{if(ytPlayer&&ytPlayer.destroy)ytPlayer.destroy()}catch(e){}ytPlayer=null;ytReady=false;q('#modalPlayer').innerHTML='';clearTimeout(retryTimer);retryTimer=setTimeout(function(){makePlayer(currentVideo,true);b.disabled=false;b.textContent='↻ Thử lại';q('#modalHelp').textContent='Đã tải lại. Nếu WebView chặn tự phát, chạm ▶ Phát.'},250)};
q('#settingsBtn').onclick=function(){q('#settingsModal').classList.remove('hidden')};q('#settingsClose').onclick=function(){q('#settingsModal').classList.add('hidden')};
q('#fitButton').onclick=function(){document.documentElement.style.zoom=document.documentElement.style.zoom==='0.9'?'1':'0.9'};
q('#videoFullscreen').onclick=function(){var p=q('#playerWrap');if(!p)return;var fn=p.requestFullscreen||p.webkitRequestFullscreen||p.msRequestFullscreen;if(fn){try{fn.call(p)}catch(e){}}else{document.body.className=document.body.className.replace(/\s*soft-fullscreen/g,'')+' soft-fullscreen'}};
function fsState(){var on=!!(document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement)||document.body.className.indexOf('soft-fullscreen')>=0;var ex=q('#exitFullscreen'),vf=q('#videoFullscreen');if(ex)ex.className=on?'small focusable':'small focusable hidden';if(vf)vf.className=on?'small focusable hidden':'small focusable'}
document.addEventListener('fullscreenchange',fsState);document.addEventListener('webkitfullscreenchange',fsState);
var exf=q('#exitFullscreen');if(exf)exf.onclick=function(){var d=document,fn=d.exitFullscreen||d.webkitExitFullscreen||d.msExitFullscreen;if(d.fullscreenElement||d.webkitFullscreenElement||d.msFullscreenElement){if(fn)try{fn.call(d)}catch(e){}}document.body.className=document.body.className.replace(/\s*soft-fullscreen/g,'');fsState();var cv=q('#changeVideo');if(cv)cv.click()};
status.textContent='CarTube sẵn sàng · chọn danh mục hoặc tìm kiếm YouTube.';
})();
(function(){
var cv=q('#changeVideo'),ip=q('#inlinePlay'),ir=q('#inlineRetry'),fr=q('#youtubeFrame');
if(cv)cv.onclick=function(){document.body.className=document.body.className.replace(/\s*player-mode/g,'');if(fr)fr.src='';var w=q('#playerWrap');if(w)w.className=w.className.replace(/\s*playing/g,'');var p=q('#playerPlaceholder');if(p)p.style.display='';var ic=q('#inlineControls');if(ic)ic.className='inline-controls hidden';if(cv)cv.className='small focusable hidden';var ex=q('#exitFullscreen');if(ex)ex.className='small focusable hidden';setTimeout(function(){if(results)results.scrollTop=browseScroll},0)};
if(ip)ip.onclick=function(){if(!currentVideo)return;if(fr)fr.src='https://www.youtube.com/embed/'+encodeURIComponent(currentVideo.id)+'?autoplay=1&playsinline=1&rel=0'};
if(ir)ir.onclick=function(){if(!currentVideo)return;if(fr){fr.src='about:blank';setTimeout(function(){fr.src='https://www.youtube.com/embed/'+encodeURIComponent(currentVideo.id)+'?autoplay=1&playsinline=1&rel=0'},180)}};
})();
(function(){
var recent=q('#recentBtn'),saved=q('#savedBtn');
if(recent)recent.onclick=function(){try{var a=JSON.parse(localStorage.getItem('aptvRecent')||'[]');render(a);status.textContent=a.length?a.length+' video đã mở gần đây':'Chưa có video gần đây'}catch(e){render([])}};
if(saved)saved.onclick=function(){try{var a=JSON.parse(localStorage.getItem('aptvSaved')||'[]');render(a);status.textContent=a.length?a.length+' bài đã lưu':'Chưa có bài đã lưu'}catch(e){render([])}};
})();