(function(){
function e(id){return document.getElementById(id)}
var d=e('destination'),state=e('gpsState'),speed=e('speed'),dest=e('destText'),rs=e('routeState'),start=e('startNav'),hint=e('turnHint'),dist=e('routeDistance'),eta=e('routeEta'),lastPos=null,routeLayer=null,me=null,target=null;
var map=L.map('map',{zoomControl:true}).setView([21.8233,105.2181],13);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
function km(m){return m<1000?Math.round(m)+' m':(m/1000).toFixed(m<10000?1:0)+' km'}
function time(sec){var m=Math.round(sec/60);if(m<60)return m+' phút';return Math.floor(m/60)+' giờ '+(m%60)+' phút'}
function setMe(lat,lon,center){lastPos={latitude:lat,longitude:lon};if(!me)me=L.circleMarker([lat,lon],{radius:8,weight:3,fillOpacity:1}).addTo(map).bindTooltip('Vị trí hiện tại');else me.setLatLng([lat,lon]);if(center)map.setView([lat,lon],15)}
function geocode(q,cb){fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=vn&q='+encodeURIComponent(q),{headers:{'Accept-Language':'vi'}}).then(function(r){return r.json()}).then(function(a){if(a&&a[0])cb(null,{lat:+a[0].lat,lon:+a[0].lon,name:a[0].display_name});else cb(new Error('notfound'))}).catch(function(x){cb(x)})}
function routeTo(q){if(!lastPos){rs.textContent='Đang chờ GPS';hint.textContent='Cần vị trí hiện tại để tính tuyến.';gps(function(){routeTo(q)});return}rs.textContent='Đang tìm tuyến...';geocode(q,function(err,p){if(err){rs.textContent='Không tìm thấy điểm đến';hint.textContent='Hãy thử tên địa điểm cụ thể hơn.';return}target=p;dest.textContent=q;if(routeLayer){map.removeLayer(routeLayer);routeLayer=null}var u='https://router.project-osrm.org/route/v1/driving/'+lastPos.longitude+','+lastPos.latitude+';'+p.lon+','+p.lat+'?overview=full&geometries=geojson&steps=true';fetch(u).then(function(r){return r.json()}).then(function(x){if(!x.routes||!x.routes[0])throw 0;var r=x.routes[0];routeLayer=L.geoJSON(r.geometry,{className:'route-line',style:{weight:7,opacity:.9}}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[35,35]});dist.textContent=km(r.distance);eta.textContent=time(r.duration);rs.textContent='Tuyến sẵn sàng';var leg=r.legs&&r.legs[0],step=leg&&leg.steps&&leg.steps[0];hint.textContent=step&&step.name?'Bắt đầu theo '+step.name+'. Tuyến đã được vẽ trực tiếp trên bản đồ.':'Tuyến đã được vẽ trực tiếp trên bản đồ.';start.href='https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(lastPos.latitude+','+lastPos.longitude)+'&destination='+encodeURIComponent(p.lat+','+p.lon)+'&travelmode=driving'}).catch(function(){rs.textContent='Không tính được tuyến';hint.textContent='Dịch vụ định tuyến đang không phản hồi. Có thể dùng nút Bắt đầu dẫn đường để mở Google Maps.'})})}
e('routeBtn').onclick=function(){var q=(d.value||'').replace(/^\s+|\s+$/g,'');if(q)routeTo(q)};
e('clear').onclick=function(){d.value='';d.focus()};
var qs=document.querySelectorAll('.quick button');for(var i=0;i<qs.length;i++)qs[i].onclick=function(){d.value=this.getAttribute('data-q');routeTo(d.value)};
e('voice').onclick=function(){var SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){rs.textContent='Không hỗ trợ giọng nói';return}var r=new SR();r.lang='vi-VN';r.interimResults=false;r.onresult=function(x){d.value=x.results[0][0].transcript;routeTo(d.value)};r.onerror=function(){rs.textContent='Không nhận được giọng nói'};r.start()};
function gps(cb){if(!navigator.geolocation){state.textContent='Không hỗ trợ GPS';return}state.textContent='Đang lấy GPS...';navigator.geolocation.getCurrentPosition(function(p){setMe(p.coords.latitude,p.coords.longitude,true);state.textContent='GPS hoạt động';if(cb)cb()},function(){state.textContent='Chưa cấp quyền GPS'},{enableHighAccuracy:true,maximumAge:2000,timeout:10000})}
if(navigator.geolocation)navigator.geolocation.watchPosition(function(p){setMe(p.coords.latitude,p.coords.longitude,false);state.textContent='GPS hoạt động';var s=p.coords.speed;if(typeof s==='number'&&s>=0)speed.textContent=Math.round(s*3.6)},function(){state.textContent='Chưa cấp quyền GPS'},{enableHighAccuracy:true,maximumAge:1500,timeout:10000});
e('locate').onclick=function(){gps()};
gps();
})();