(function(){
var PLAYLIST='https://iptv-org.github.io/iptv/countries/vn.m3u',LOCAL_PLAYLIST='channels.json',channels=[],current=-1,group='all',hls=null,playToken=0;
function q(s){return document.querySelector(s)}function qa(s){return document.querySelectorAll(s)}
function favs(){try{return JSON.parse(localStorage.getItem('aptvTvFav')||'[]')}catch(e){return[]}}
function isFav(id){return favs().indexOf(id)>=0}
function toggleFav(id){var a=favs(),i=a.indexOf(id);if(i>=0)a.splice(i,1);else a.push(id);localStorage.setItem('aptvTvFav',JSON.stringify(a));render()}
function parseM3U(txt){var lines=txt.replace(/\r/g,'').split('\n'),out=[],meta=null;for(var i=0;i<lines.length;i++){var line=lines[i].replace(/^\s+|\s+$/g,'');if(line.indexOf('#EXTINF:')===0){var n=line.lastIndexOf(',');var attrs=line.substring(0,n),name=n>=0?line.substring(n+1):'Kênh TV';function attr(k){var m=new RegExp(k+'="([^"]*)"').exec(attrs);return m?m[1]:''}meta={name:name||attr('tvg-name')||'Kênh TV',logo:attr('tvg-logo'),group:attr('group-title')||'Việt Nam',id:attr('tvg-id')||('ch'+out.length)}}else if(meta&&line&&line.charAt(0)!=='#'){meta.url=line;out.push(meta);meta=null}}return out}
function normalizeLocal(a){var out=[];for(var i=0;i<(a||[]).length;i++){var c=a[i]||{};out.push({id:c.id||('local'+i),name:c.name||'Kênh TV',logo:c.logo||'',group:c.group||'Dự phòng',url:c.url||'',urls:c.urls||[],localFallback:true})}return out}
function loadLocal(done){var x=new XMLHttpRequest();x.open('GET',LOCAL_PLAYLIST+'?ts='+Date.now(),true);x.onreadystatechange=function(){if(x.readyState!==4)return;try{done(x.status>=200&&x.status<300?normalizeLocal(JSON.parse(x.responseText)):[])}catch(e){done([])}};x.send()}
function load(){q('#tvCount').textContent='Đang tải...';var x=new XMLHttpRequest();x.open('GET',PLAYLIST,true);x.onreadystatechange=function(){if(x.readyState!==4)return;if(x.status>=200&&x.status<300){channels=parseM3U(x.responseText);q('#tvCount').textContent=channels.length+' kênh';q('#tvStatus').textContent='Nguồn chính đã sẵn sàng';render();var last=localStorage.getItem('aptvTvLast');if(last)openChannel(last)}else{loadLocal(function(a){channels=a;q('#tvCount').textContent=a.length?a.length+' kênh dự phòng':'Không tải được danh sách';q('#tvStatus').textContent=a.length?'Đang dùng nguồn dự phòng cục bộ':'Không có nguồn TV khả dụng';render()})}};x.send()}
function filtered(){var term=(q('#tvSearch').value||'').toLowerCase(),a=[];for(var i=0;i<channels.length;i++){var c=channels[i],g=c.group||'';if(group==='fav'&&!isFav(c.id))continue;if(group!=='all'&&group!=='fav'&&g.toLowerCase().indexOf(group.toLowerCase())<0)continue;if(term&&(c.name+' '+g).toLowerCase().indexOf(term)<0)continue;a.push(c)}return a}
function sourceList(c){var a=[];if(c.url)a.push(c.url);for(var i=0;i<(c.urls||[]).length;i++)if(a.indexOf(c.urls[i])<0)a.push(c.urls[i]);return a}
function playUrlList(c,index,token){var v=q('#tvVideo'),list=sourceList(c);if(!list.length){q('#tvStatus').textContent='Kênh chưa có nguồn phát.';return}if(index>=list.length){q('#tvStatus').textContent='Tất cả nguồn của kênh này đang lỗi.';return}var url=list[index];q('#tvStatus').textContent=index?'Đang thử nguồn dự phòng '+(index+1)+'/'+list.length:'Đang kết nối nguồn chính...';if(hls){try{hls.destroy()}catch(e){}hls=null}var failed=false;function fallback(){if(failed||token!==playToken)return;failed=true;setTimeout(function(){playUrlList(c,index+1,token)},250)};v.onerror=fallback;if(v.canPlayType('application/vnd.apple.mpegurl')){v.src=url;var p=v.play();if(p&&p.catch)p.catch(fallback);v.onplaying=function(){if(token===playToken)q('#tvStatus').textContent=index?'Đang phát nguồn dự phòng':'Đang phát ổn định'}}else if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:true,maxBufferLength:20});hls.loadSource(url);hls.attachMedia(v);hls.on(Hls.Events.MANIFEST_PARSED,function(){var p=v.play();if(p&&p.catch)p.catch(fallback)});hls.on(Hls.Events.ERROR,function(e,data){if(data&&data.fatal)fallback()});v.onplaying=function(){if(token===playToken)q('#tvStatus').textContent=index?'Đang phát nguồn dự phòng':'Đang phát ổn định'}}else{v.src=url;var p2=v.play();if(p2&&p2.catch)p2.catch(fallback)}}
function openChannel(id){for(var i=0;i<channels.length;i++)if(channels[i].id===id){current=i;var c=channels[i];q('#tvNow').textContent=c.name+' · '+(c.group||'TV');q('#tvVideo').style.display='block';q('#tvPlaceholder').style.display='none';playToken++;playUrlList(c,0,playToken);localStorage.setItem('aptvTvLast',id);localStorage.setItem('aptvTvRecent',JSON.stringify({id:c.id,name:c.name,group:c.group||'TV',at:Date.now()}));render();return}}
function card(c,quick){var d=document.createElement('div');d.className=quick?'tv-quick-item':'tv-channel-card';var b=document.createElement('button');b.className='focusable tv-channel-open'+(current>=0&&channels[current].id===c.id?' active':'');var logo=c.logo?'<img class="tv-logo-img" src="'+c.logo+'" onerror="this.style.display=\'none\'">':'<span class="tv-logo">'+c.name.substring(0,6)+'</span>';b.innerHTML=logo+'<span><b>'+c.name+'</b><small>'+(c.group||'Việt Nam')+'</small></span>';b.onclick=function(){openChannel(c.id)};d.appendChild(b);if(!quick){var f=document.createElement('button');f.className='tv-fav focusable';f.textContent=isFav(c.id)?'★':'☆';f.onclick=function(){toggleFav(c.id)};d.appendChild(f)}return d}
function render(){var a=filtered(),box=q('#tvChannels'),quick=q('#tvQuickList');box.innerHTML='';quick.innerHTML='';for(var i=0;i<a.length;i++){box.appendChild(card(a[i],false));quick.appendChild(card(a[i],true))}q('#tvCount').textContent=a.length+' / '+channels.length+' kênh'}
function step(n){if(!channels.length)return;current=current<0?0:(current+n+channels.length)%channels.length;openChannel(channels[current].id)}
q('#tvSearch').oninput=function(){syncTvSearch();render()};
function syncTvSearch(){var i=q('#tvSearch'),w=i&&i.parentNode;if(w)w.className=i.value?'tv-search-wrap has-text':'tv-search-wrap'}
var clear=q('#tvClearSearch');if(clear)clear.onclick=function(){var i=q('#tvSearch');i.value='';syncTvSearch();render();i.focus()};
var voice=q('#tvVoiceSearch');if(voice)voice.onclick=function(){
 var SR=window.SpeechRecognition||window.webkitSpeechRecognition;
 if(!SR){q('#tvStatus').textContent='Trình duyệt này chưa hỗ trợ tìm kiếm giọng nói.';return}
 var r=new SR();r.lang='vi-VN';r.interimResults=false;r.maxAlternatives=1;
 voice.textContent='●';q('#tvStatus').textContent='Đang nghe tên kênh...';
 r.onresult=function(e){var t=e.results&&e.results[0]&&e.results[0][0]?e.results[0][0].transcript:'';q('#tvSearch').value=t;syncTvSearch();render();q('#tvStatus').textContent=t?'Đã tìm: '+t:'Không nhận được tên kênh'};
 r.onerror=function(){q('#tvStatus').textContent='Không nhận được giọng nói. Hãy thử lại.'};
 r.onend=function(){voice.textContent='🎤'};
 try{r.start()}catch(e){}
};syncTvSearch();var gs=qa('[data-group]');for(var i=0;i<gs.length;i++)gs[i].onclick=function(){group=this.getAttribute('data-group');for(var j=0;j<gs.length;j++)gs[j].className='chip focusable';this.className='chip focusable active';render()};
q('#tvPrev').onclick=function(){step(-1)};q('#tvNext').onclick=function(){step(1)};q('#tvPrevFoot').onclick=function(){step(-1)};q('#tvNextFoot').onclick=function(){step(1)};q('#tvListFoot').onclick=function(){q('#tvChannels').scrollIntoView({behavior:'smooth',block:'start'})};
q('#tvFullscreen').onclick=function(){var p=q('#tvPlayerWrap'),fn=p.requestFullscreen||p.webkitRequestFullscreen;if(fn)try{fn.call(p)}catch(e){}};
function updateMini(){var bar=q('#miniMediaBar'),title=q('#miniMediaTitle'),open=q('#miniMediaOpen');if(!bar||!title)return;try{var v=JSON.parse(localStorage.getItem('aptvNowPlaying')||'null');if(v&&v.id){title.textContent=v.title||'Video YouTube';if(open)open.href='youtube.html?video='+encodeURIComponent(v.id);bar.className='mini-media'}else bar.className='mini-media hidden'}catch(e){bar.className='mini-media hidden'}}
var mc=q('#miniMediaClose');if(mc)mc.onclick=function(){localStorage.removeItem('aptvNowPlaying');updateMini()};updateMini();
load();
})();