(function(){
var PLAYLIST='https://iptv-org.github.io/iptv/countries/vn.m3u',channels=[],current=-1,group='all',hls=null;
function q(s){return document.querySelector(s)}function qa(s){return document.querySelectorAll(s)}
function favs(){try{return JSON.parse(localStorage.getItem('aptvTvFav')||'[]')}catch(e){return[]}}
function isFav(id){return favs().indexOf(id)>=0}
function toggleFav(id){var a=favs(),i=a.indexOf(id);if(i>=0)a.splice(i,1);else a.push(id);localStorage.setItem('aptvTvFav',JSON.stringify(a));render()}
function parseM3U(txt){var lines=txt.replace(/\r/g,'').split('\n'),out=[],meta=null;for(var i=0;i<lines.length;i++){var line=lines[i].replace(/^\s+|\s+$/g,'');if(line.indexOf('#EXTINF:')===0){var n=line.lastIndexOf(',');var attrs=line.substring(0,n),name=n>=0?line.substring(n+1):'Kênh TV';function attr(k){var m=new RegExp(k+'="([^"]*)"').exec(attrs);return m?m[1]:''}meta={name:name||attr('tvg-name')||'Kênh TV',logo:attr('tvg-logo'),group:attr('group-title')||'Việt Nam',id:attr('tvg-id')||('ch'+out.length)}}else if(meta&&line&&line.charAt(0)!=='#'){meta.url=line;out.push(meta);meta=null}}return out}
function load(){q('#tvCount').textContent='Đang tải...';var x=new XMLHttpRequest();x.open('GET',PLAYLIST,true);x.onreadystatechange=function(){if(x.readyState!==4)return;if(x.status>=200&&x.status<300){channels=parseM3U(x.responseText);q('#tvCount').textContent=channels.length+' kênh';render();var last=localStorage.getItem('aptvTvLast');if(last)openChannel(last)}else{q('#tvCount').textContent='Không tải được danh sách'}};x.send()}
function filtered(){var term=(q('#tvSearch').value||'').toLowerCase(),a=[];for(var i=0;i<channels.length;i++){var c=channels[i],g=c.group||'';if(group==='fav'&&!isFav(c.id))continue;if(group!=='all'&&group!=='fav'&&g.toLowerCase().indexOf(group.toLowerCase())<0)continue;if(term&&(c.name+' '+g).toLowerCase().indexOf(term)<0)continue;a.push(c)}return a}
function playUrl(url){var v=q('#tvVideo');if(hls){try{hls.destroy()}catch(e){}hls=null}if(v.canPlayType('application/vnd.apple.mpegurl')){v.src=url;try{v.play()}catch(e){}}else if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:true});hls.loadSource(url);hls.attachMedia(v);hls.on(Hls.Events.MANIFEST_PARSED,function(){try{v.play()}catch(e){}})}else{v.src=url}}
function openChannel(id){for(var i=0;i<channels.length;i++)if(channels[i].id===id){current=i;var c=channels[i];q('#tvNow').textContent=c.name+' · '+(c.group||'TV');q('#tvVideo').style.display='block';q('#tvPlaceholder').style.display='none';playUrl(c.url);localStorage.setItem('aptvTvLast',id);render();return}}
function card(c,quick){var d=document.createElement('div');d.className=quick?'tv-quick-item':'tv-channel-card';var b=document.createElement('button');b.className='focusable tv-channel-open'+(current>=0&&channels[current].id===c.id?' active':'');var logo=c.logo?'<img class="tv-logo-img" src="'+c.logo+'" onerror="this.style.display=\'none\'">':'<span class="tv-logo">'+c.name.substring(0,6)+'</span>';b.innerHTML=logo+'<span><b>'+c.name+'</b><small>'+(c.group||'Việt Nam')+'</small></span>';b.onclick=function(){openChannel(c.id)};d.appendChild(b);if(!quick){var f=document.createElement('button');f.className='tv-fav focusable';f.textContent=isFav(c.id)?'★':'☆';f.onclick=function(){toggleFav(c.id)};d.appendChild(f)}return d}
function render(){var a=filtered(),box=q('#tvChannels'),quick=q('#tvQuickList');box.innerHTML='';quick.innerHTML='';for(var i=0;i<a.length;i++){box.appendChild(card(a[i],false));quick.appendChild(card(a[i],true))}q('#tvCount').textContent=a.length+' / '+channels.length+' kênh'}
function step(n){if(!channels.length)return;current=current<0?0:(current+n+channels.length)%channels.length;openChannel(channels[current].id)}
q('#tvSearch').oninput=render;var gs=qa('[data-group]');for(var i=0;i<gs.length;i++)gs[i].onclick=function(){group=this.getAttribute('data-group');for(var j=0;j<gs.length;j++)gs[j].className='chip focusable';this.className='chip focusable active';render()};
q('#tvPrev').onclick=function(){step(-1)};q('#tvNext').onclick=function(){step(1)};q('#tvPrevFoot').onclick=function(){step(-1)};q('#tvNextFoot').onclick=function(){step(1)};q('#tvListFoot').onclick=function(){q('#tvChannels').scrollIntoView({behavior:'smooth',block:'start'})};
q('#tvFullscreen').onclick=function(){var p=q('#tvPlayerWrap'),fn=p.requestFullscreen||p.webkitRequestFullscreen;if(fn)try{fn.call(p)}catch(e){}};
load();
})();